### PR TITLE
Change font color for buy me a coffee

### PR DESCRIPTION
**Pull request by keiohtani**
#63

### CODE REVIEW

**Comment by keiohtani** [comment]
## Normal view
image

## Dark mode
image

## Dark mode + Color blind mode
image

**Comment by yamila-moreno** [comment]
I came to suggest exactly this PR, this is really necessary to give the author some visibility!!! Thanks!!

**Comment by keiohtani** [comment]
> I came to suggest exactly this PR, this is really necessary to give the author some visibility!!! Thanks!!

Yes, I agree! This is such a perfect game for the outbreak. Worthwhile for recognition!

**Comment by jbowens** [comment]
Thanks! I actually originally only intended the link to be barely visible as a joke, but I forgot about dark mode, haha. Anyways, PR looks good and thanks again!

**Pull request merged**
