### PR TITLE
Add Adult Content label to English (Deep Undercover)

### PR DESCRIPTION
**Pull request by alexander89d**
This pull request addresses a very minor suggestion to add an [Adult Content] label to the "English (Deep Undercover)" word list. This will be helpful to those coming to the site who do not have prior knowledge of the Codenames: Deep Undercover board game. I had an awkward experience where I was excited to see that a the new Deep Undercover word list had been added when setting up a game including my parents and grandfather. I thought this was just more general English words (like the Duet word list) and that "Deep Undercover" just meant that they were higher-level vocabulary words. I then had to quickly set up a new game when I launched the game involving the Deep Undercover words with my family and realized that Deep Undercover words are adult themed. I totally get why this word list is included since it is reflective of an existing version of Codenames; I just think the [Adult Content] label would be consistent with the warning label on the board game's box and would help others who were not intending to create an adult content game to avoid potentially awkward situations like I encountered. :)

### CODE REVIEW

**Comment by jbowens** [comment]
Oh shoot, sorry about that! What do you think of changing the label to `[NSFW]`, just so that it's shorter? Would you recognize that label?

**Comment by alexander89d** [comment]
A shorter label makes sense so that the button text is not too long. Since the [NSFW] label might not be one that people are as widely familiar with (particularly people who are not well-versed in internet lingo), what about a label like [MA] or [R-Rated] instead?

**Comment by jbowens** [comment]
Sure, let's go with `[MA]`

**Comment by alexander89d** [comment]
OK, great, I have pushed the change to this pull request's branch with the [Adult Content] label replaced with [MA].

**Comment by jbowens** [comment]
Great, thank you!

**Pull request merged**
