### PR TITLE
Slovak wordlist

### PR DESCRIPTION
**Pull request by regressiv**
Can I make a Slovak wordlist ?

### CODE REVIEW

**Comment by regressiv** [comment]
CHROBÁK, POLE, PRSTEŇ, KYVADLO, AUSTRÁLIA, ZIMA, ROBOTNÍK, KENTAUR, ĽAD, LYŽICA, UCHO, PEC, FUTBALISTA, LÁVA, STOPKY, DELO, LIETADLO, ZADOK, FILM, KÔŠ, ZEMIAK, CESTOVATEĽ, OTEC, VÍLA, KLINEC, BERLÍN, PRACH, OSTROV, VÄZEŇ, HOKEJISTA, ČÍNA, OVCA, KNIHA, HEREC, OKNO, ČEREŠŇA, FĽAŠA, ZOMBIA, HUBA, NETOPIER, SVETLO, PREDAVAČ, KORUNA, JAŠTERICA, SKRUTKA, DRAK, YETTI, VESMÍR, KAPOR, MATKA, CESTA, HRAD, UPÍR, VOJNA, HÁK, CIRKUS, RIEKA, LÍŠKA, PES, ŽEHLIČKA, AMERIKA, ŠÍPKA, BUNKA, ZÁKUSOK, KOMÉTA, KOZA, SOĽ, VÍRUS, VÁHA, PEKING, PREZIDENT, MLIEKO, AUTO, BRATISLAVA, GUMA, SMRŤ, HLINA, ORGÁN, DÉMON, MRAVEC, ŽOBRÁK, TELEFÓN, DINOSAURUS, GRÉCKO, PANNA, VOZ, KVAPEĽ, GITARA, OROL, BRAT, KAKTUS, JADRO, ZRKADLO, NEMOCNICA, STENA, OMÁČKA, KORENIE, UHLIE, PAS, DÁŽĎ, PODNIKATEĽ, TRÚBA, BETÓN, SNEH, ČELO, PÓL, ZEBRA, VEŽA, KRÍŽ, ROLA, REŤAZ, LASER, MRAKODRAP, CESTA, ZÁKON, LOS, IHLA, MAĎAR, ŠŤASTIE, CHOROBA, TOPOĽ, NEMECKO, ZEM, SUKŇA, KURA, HORA, STOLIČKA, BANKÁR, HODINKY, VEĽRYBA, FYZIK, KOREŇ, KLOBÚK, LOPATA, LOCHNESKA, BANÁN, ÚRAD, ÚDOLIE, BÁSNIK, PÍLA, MRÁZ, PAPRIKA, KRČMA, PRÁČKA, POLIEVKA, KAMARÁT, DVERE, PLACKA, RAKETA, DRÔT, ČECH, NÔŽ, SNEŽIENKA, LOPTA, KLADIVO, SYR, NEPRIATEĽ, MYŠ, SLNKO, LÁTKA, NOC, MUCHOTRÁVKA, REBRO, KRÁĽ, ČERT, FLAUTA, KINO, VZDUCH, OHEŇ, PRÁCA, TLAČIDLO, KLIEŠTE, KOŠEĽA, MARS, OKULIARE, MOSKVA, TRÁVA, LOKOMOTÍVA, PLÁŠŤ, HRNIEC, PARK, OKO, PALICA, OBCHOD, HLAVA, PANVA, SLOVÁK, MOTÝLIK, FRANCÚZSKO, DOM, MÚKA, PAPAGÁJ, DIAMANT, HREBEŇ, FIGÚRKA, AMERIČAN, ŽELEZO, ČARODEJNÍK, LIMONÁDA, POPOL, KLOKAN, KAMEŇ, KĽÚČ, AFRIKA, VODIČ, SALÁMA, SKLO, DŽUNGLA, BIOLÓG, RADOSŤ, ZÁMOK, ZUB, TALIANSKO, DOKTOR, PAPUČA, PRASA, VLAK, CHOBOTNICA, KOCKA, PARNÍK, SPRÁVA, MOTORKA, DUCH, KOMÍN, KOHÚTIK, ROZPRÁVKA, KAMIÓN, JABĹČKO, SMREK, STRANA, MATEMATIK, TULIPÁN, SESTRA, KLAUN, KOSA, HUDBA, KOBYLKA, ANGLICKO, MORE, TANIER, PARADAJKA, SMOLA, VOJVODCA, MEDVEĎ, RUČIČKA, BRUCHO, DREVO, KROKODÍL, HOLANĎAN, ŽERIAV, VETERNÍK, VTÁKOPYSK, CHLIEB, ŠPANIEL, LUPIČ, PLAST, TRPASLÍK, PALEC, VODA, HRA, LAMPA, CICAVEC, NOHAVICE, SLON, CERUZKA, VRCHOL, KRAVA, BRAZÍLIA, HLINÍK, ÁZIA, KMEŇ PODVODNÍK, PÚŠŤ, JEŽKO, JASKYŇA VIEDEŇ, PLYN, JESEŇ, BUBLINA, ŠALÁT, ŠKRIATOK, NOHA, PANÁK, KANADA, KVET, PAVÚK, POČÍTAČ, MESIAC, PARÍŽ, SEDLIAK, KAPUSTA, VENUŠA, LEV, ČOKOLÁDA, SEDMOKRÁSKA, KOZMONAUT, PROGRAMÁTOR, VIEČKO, ANJEL, LONDÝN, KNEDĽA, ZLATO, LETO, MAČKA, TIGER, KER, MÄSO, FILOZOF, JAZVEC, VIERA, LIST, NOS, RYS, KLÁVESNICA, KABÁT, ZVONČEK, POLICAJT, HVIEZDA, ŠŤUKA, TELEVÍZIA, SEKERA, UTERÁK, HLAS, DIEŤA, PRINCEZNÁ, SLIVKA, PLANÉTA, MEČ, UMELEC, BRADA, JAR, OBOR, KOŠICE, STRIEBRO, ŠOŠOVIČKA, ŠKORPIÓN, PONOŽKA, DUB, SUPERHRDINA, BASA, KARTA, JAZDEC, ORECH, POMARANČ, RUŽA, KORYTNAČKA, PIVO, SVIEČKA, DEDINA, ŠPAGETA, SKRUTKOVAČ, STROM, LÚKA, POÉZIA, KEFA, PLOT, VLNA, LÁSKA, POVRAZ, MRKVA, ATLÉT, OBÁLKA, SRDCE, TUČNIAK, JEDNOROŽEC, DÝKA, CUKOR, UČITEĽ, KLAVÍR, STANICA, PIŠTOĽ, ŠKOLA, ROH, SPEVÁK, MIER, PAPIER, KÚZLO, VIDLIČKA, AUTOBUS, VIETOR, ROPA, LES, STRELEC, KNIŽNICA, PLASTELÍNA, MELÓN, ČAPICA, CINTORÍN, VODNÍK, VEDEC, ŽRALOK, JAZYK, RÁDIO, KOLENO, VAJCE, MESTO, KOLOBEŽKA, GUĽA, BRÁNA, RUS

**Comment by jbowens** [comment]
@regressiv Great, thanks for the list! I'll add it shortly.

**Comment by regressiv** [comment]
Thanks! I found some mistakes, so here it is once again:

CHROBÁK, POLE, PRSTEŇ, KYVADLO, AUSTRÁLIA, ZIMA, ROBOTNÍK, KENTAUR, ĽAD, LYŽICA, UCHO, PEC, FUTBALISTA, LÁVA, STOPKY, DELO, LIETADLO, ZADOK, FILM, KÔŠ, ZEMIAK, CESTOVATEĽ, OTEC, VÍLA, KLINEC, BERLÍN, PRACH, OSTROV, VÄZEŇ, HOKEJISTA, ČÍNA, OVCA, KNIHA, HEREC, OKNO, ČEREŠŇA, FĽAŠA, ZOMBIA, HUBA, NETOPIER, SVETLO, PREDAVAČ, KORUNA, JAŠTERICA, SKRUTKA, DRAK, YETTI, VESMÍR, KAPOR, MATKA, CESTA, HRAD, UPÍR, VOJNA, HÁK, CIRKUS, RIEKA, LÍŠKA, PES, ŽEHLIČKA, AMERIKA, ŠÍPKA, BUNKA, ZÁKUSOK, KOMÉTA, KOZA, SOĽ, VÍRUS, VÁHA, PEKING, PREZIDENT, MLIEKO, AUTO, BRATISLAVA, GUMA, SMRŤ, HLINA, ORGÁN, DÉMON, MRAVEC, ŽOBRÁK, TELEFÓN, DINOSAURUS, GRÉCKO, PANNA, VOZ, KVAPEĽ, GITARA, OROL, BRAT, KAKTUS, JADRO, ZRKADLO, NEMOCNICA, STENA, OMÁČKA, KORENIE, UHLIE, PAS, DÁŽĎ, PODNIKATEĽ, TRÚBA, BETÓN, SNEH, ČELO, PÓL, ZEBRA, VEŽA, KRÍŽ, ROLA, REŤAZ, LASER, MRAKODRAP, CESTA, ZÁKON, LOS, IHLA, MAĎAR, ŠŤASTIE, CHOROBA, TOPOĽ, NEMECKO, ZEM, SUKŇA, KURA, HORA, STOLIČKA, BANKÁR, HODINKY, VEĽRYBA, FYZIK, KOREŇ, KLOBÚK, LOPATA, LOCHNESKA, BANÁN, ÚRAD, ÚDOLIE, BÁSNIK, PÍLA, MRÁZ, PAPRIKA, KRČMA, PRÁČKA, POLIEVKA, KAMARÁT, DVERE, PLACKA, RAKETA, DRÔT, ČECH, NÔŽ, SNEŽIENKA, LOPTA, KLADIVO, SYR, NEPRIATEĽ, MYŠ, SLNKO, LÁTKA, NOC, MUCHOTRÁVKA, REBRO, KRÁĽ, ČERT, FLAUTA, KINO, VZDUCH, OHEŇ, PRÁCA, TLAČIDLO, KLIEŠTE, KOŠEĽA, MARS, OKULIARE, MOSKVA, TRÁVA, LOKOMOTÍVA, PLÁŠŤ, HRNIEC, PARK, OKO, PALICA, OBCHOD, HLAVA, PANVA, SLOVÁK, MOTÝLIK, FRANCÚZSKO, DOM, MÚKA, PAPAGÁJ, DIAMANT, HREBEŇ, FIGÚRKA, AMERIČAN, ŽELEZO, ČARODEJNÍK, LIMONÁDA, POPOL, KLOKAN, KAMEŇ, KĽÚČ, AFRIKA, VODIČ, SALÁMA, SKLO, DŽUNGLA, BIOLÓG, RADOSŤ, ZÁMOK, ZUB, TALIANSKO, DOKTOR, PAPUČA, PRASA, VLAK, CHOBOTNICA, KOCKA, PARNÍK, SPRÁVA, MOTORKA, DUCH, KOMÍN, KOHÚTIK, ROZPRÁVKA, KAMIÓN, JABĹČKO, SMREK, STRANA, MATEMATIK, TULIPÁN, SESTRA, KLAUN, KOSA, HUDBA, KOBYLKA, ANGLICKO, MORE, TANIER, PARADAJKA, SMOLA, VOJVODCA, MEDVEĎ, RUČIČKA, BRUCHO, DREVO, KROKODÍL, HOLANĎAN, ŽERIAV, VETERNÍK, VTÁKOPYSK, CHLIEB, ŠPANIEL, LUPIČ, PLAST, TRPASLÍK, PALEC, VODA, HRA, LAMPA, CICAVEC, NOHAVICE, SLON, CERUZKA, VRCHOL, KRAVA, BRAZÍLIA, HLINÍK, ÁZIA, KMEŇ, PODVODNÍK, PÚŠŤ, JEŽKO, JASKYŇA, VIEDEŇ, PLYN, JESEŇ, BUBLINA, ŠALÁT, ŠKRIATOK, NOHA, PANÁK, KANADA, KVET, PAVÚK, POČÍTAČ, MESIAC, PARÍŽ, SEDLIAK, KAPUSTA, VENUŠA, LEV, ČOKOLÁDA, SEDMOKRÁSKA, KOZMONAUT, PROGRAMÁTOR, VIEČKO, ANJEL, LONDÝN, KNEDĽA, ZLATO, LETO, MAČKA, TIGER, KER, MÄSO, FILOZOF, JAZVEC, VIERA, LIST, NOS, RYS, KLÁVESNICA, KABÁT, ZVONČEK, POLICAJT, HVIEZDA, ŠŤUKA, TELEVÍZIA, SEKERA, UTERÁK, HLAS, DIEŤA, PRINCEZNÁ, SLIVKA, PLANÉTA, MEČ, UMELEC, BRADA, JAR, OBOR, KOŠICE, STRIEBRO, ŠOŠOVIČKA, ŠKORPIÓN, PONOŽKA, DUB, SUPERHRDINA, BASA, KARTA, JAZDEC, ORECH, POMARANČ, RUŽA, KORYTNAČKA, PIVO, SVIEČKA, DEDINA, ŠPAGETA, SKRUTKOVAČ, STROM, LÚKA, POÉZIA, KEFA, PLOT, VLNA, LÁSKA, POVRAZ, MRKVA, ATLÉT, OBÁLKA, SRDCE, TUČNIAK, JEDNOROŽEC, DÝKA, CUKOR, UČITEĽ, KLAVÍR, STANICA, PIŠTOĽ, ŠKOLA, ROH, SPEVÁK, MIER, PAPIER, KÚZLO, VIDLIČKA, AUTOBUS, VIETOR, ROPA, LES, STRELEC, KNIŽNICA, PLASTELÍNA, MELÓN, ČAPICA, CINTORÍN, VODNÍK, VEDEC, ŽRALOK, JAZYK, RÁDIO, KOLENO, VAJCE, MESTO, KOLOBEŽKA, GUĽA, BRÁNA, RUS

**Comment by jbowens** [comment]
Thanks @regressiv, I just merged your word list in 06b683f.

**Pull request closed without merging**
