### PR TITLE
Multiple language support

### PR DESCRIPTION
**Pull request by alexhans1**
Main objective is to be able to start a game with languages other than English.

I added German 🇩🇪as a language but including more languages 🇫🇷🇮🇹🇨🇳🇪🇸🇧🇷should be easy now by simply adding them to the new `words.json` file.

Also converted the two main react files into function components using hooks.

Hope this makes sense... 🚀

### CODE REVIEW

**Comment by jbowens** [comment]
This is a pretty big diff! It looks like most of the churn is from style changes, which makes it hard to review the substance of the diff. Do you mind splitting out the style changes into a separate PR if you want to apply those?

**Comment by alexhans1** [comment]
sure. let me mark this as WIP in the meantime

**Comment by alexhans1** [comment]
I added another two merge requests.
- one for the npm scripts and
- one that only prettifies the code.

If those could be merged, I could rebase this branch onto master and reopen the MR.

**Comment by alexhans1** [comment]
done. The remaining changes include the conversion of class components to functional components and the actual multiple language support

**Comment by jbowens** [comment]
Thanks!

**Pull request merged**
